export enum OptionKey {
  copy = "copy",
  paste = "paste",
  cut = "cut",
  insertRowUp = "insertRowUp",
  insertRowDown = "insertRowDown",
  insertRowMore = "insertRowMore",
  insertColumnBefore = "insertColumnBefore",
  insertColumnAfter = "insertColumnAfter",
  insertColumnMore = "insertColumnMore",
  removeRow = "removeRow",
  removeColumn = "removeColumn",
  clearCell = "clearCell",
  removeCellUp = "removeCellUp",
  removeCellLeft = "removeCellLeft",
}
